name: Issue report
description: intergration or entities is not working right
body:
  - type: input
    attributes:
      label: HA core version
      placeholder: 2023.4.2
  - type: input
    validations:
      required: true
    attributes:
      label: Intergration version
      placeholder: 0.3.18
  - type: input
    validations:
      required: true
    attributes:
      label: Device type and model
      placeholder: Air Conditioner 22012225
      description: Can be found in Settings -> Devices & Services -> Midea AC LAN -> Devices -> Device Info
  - type: textarea
    validations:
      required: true
    attributes:
      label: The description of problem
  - type: textarea
    attributes:
      label: The logs
      description: Should enable the debug log of Midea AC LAN, and post or upload the log when the error occurs to here
  - type: textarea
    attributes:
      label: Anything else